{% set name = "graypy" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd8dc4a721de1278576d92db10ac015e99b4e480cf1b18892e79429fd9236e16

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - graypy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/severb/graypy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python logging handler that sends messages in GELF (Graylog Extended Log Format).
  doc_url: https://pypi.org/project/graypy/
  dev_url: https://github.com/severb/graypy

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
